export const doctorData = [
  {
    fullName: 'Arjun Mehta',
    email: 'arjun.mehta@medthread.com',
    username: 'arjun_mehta',
    specialty: 'Cardiology',
    subSpecialty: 'Interventional Cardiology',
    city: 'Mumbai',
    state: 'Maharashtra',
    district: 'Mumbai City',
    pincode: '400001',
    phone: '+91-9876543210',
    hospitalAffiliation: 'Lilavati Hospital',
    clinicAddress: 'Bandra West, Mumbai, Maharashtra 400050',
    medicalLicenseNumber: 'MH-CARD-2010-12345',
    licenseIssuingAuthority: 'Maharashtra Medical Council',
    yearsOfExperience: 14,
    graduationYear: 2010,
    medicalUniversity: 'Grant Medical College, Mumbai',
    bio: 'Interventional cardiologist with expertise in angioplasty and cardiac catheterization. Passionate about preventive cardiology and lifestyle modifications for heart health.'
  },
  {
    fullName: 'Priya Nair',
    email: 'priya.nair@medthread.com',
    username: 'priya_nair',
    specialty: 'Dermatology',
    subSpecialty: 'Cosmetic Dermatology',
    city: 'Chennai',
    state: 'Tamil Nadu',
    district: 'Chennai',
    pincode: '600001',
    phone: '+91-9876543211',
    hospitalAffiliation: 'Apollo Hospitals Chennai',
    clinicAddress: 'Greams Road, Chennai, Tamil Nadu 600006',
    medicalLicenseNumber: 'TN-DERM-2012-67890',
    licenseIssuingAuthority: 'Tamil Nadu Medical Council',
    yearsOfExperience: 12,
    graduationYear: 2012,
    medicalUniversity: 'Madras Medical College',
    bio: 'Dermatologist specializing in acne treatment, anti-aging procedures, and skin cancer screening. Advocate for holistic skin health.'
  },
